# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Animal Data Laboratory
subtitle: "Adventure of lifetime with animal science; modeling; machine learning; R; Shiny; Docker"
email: ruminoreticulum@gmail.com
name: Youngjun Na
description: animal science; nutrition modeling; R; Shiny; machine learning
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://youngjunna.github.io" # the base hostname & protocol for your site
cover: "https://images.unsplash.com/photo-1569261201323-859593170d41?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1234&q=80"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"
# google_analytics: "UA-111371471-1"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
ga_tracking_id: "UA-111371471-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: Animal nutrition journal report
    desc: "Posts for Animal nutrition journal report"

  - cat: R
    desc: "Posts for R programming"

  - cat: R packages
    desc: "Posts for introducing the R packages"

  - cat: Presentation
    desc: "Presentation files"

  - cat: Note
    desc: "Note"


# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: GitHub
    icon: github
    username: Youngjun Na
    url: https://github.com/youngjunna
    desc: GitHub
    share: true

  - name: Instagram
    icon: instagram
    username: Youngjun Na
    url: https://www.instagram.com/youngjun_na/
    desc: Follow me on Instagram
    share: true


# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
