# Site settings
email: ruminoreticulum@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: YN
description: 배우는 사람
url: ""
twitter_username:
default_img:

# Profile settings
name: Youngjun Na
profile_img:
profile: "배우는 사람"
social:
  github: youngjunna

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
