# Site settings
email: ruminoreticulum@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: "UA-111371471-1"

# SEO settings
title: YN's research note
description: 배우는 사람
url: ""
twitter_username:
default_img:

# Profile settings
name: Youngjun Na
profile_img: https://avatars1.githubusercontent.com/u/28377612?s=460&v=4
profile: "test /n ruminoreticulum@gmail.com"
social:
  github: "https://github.com/YoungjunNa"

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
